version: '3.8'

services:
  auth_service:
    build:
      context: ./AuthenticationService
    ports:
      - '3001:3001'
    depends_on:
      - auth_db

  auth_db:
    build:
      context: ./AuthenticationService
    volumes:
      - ./AuthenticationService/database_auth.sqlite:/app/database_auth.sqlite

  user_service:
    build:
      context: ./UserService
    ports:
      - '3002:3002'
    depends_on:
      - user_db

  user_db:
    build:
      context: ./UserService
    volumes:
      - ./UserService/database_user.sqlite:/app/database_user.sqlite

  encryption_service:
    build:
      context: ./EncryptionService
    ports:
      - '3003:3003'
    depends_on:
      - encryption_db

  encryption_db:
    build:
      context: ./EncryptionService
    volumes:
      - ./EncryptionService/database_encryption.sqlite:/app/database_encryption.sqlite

  userdata_service:
    build:
      context: ./UserDataService
    ports:
      - '3005:3005'
    depends_on:
      - userdata_db

  userdata_db:
    build:
      context: ./UserDataService
    volumes:
      - ./UserDataService/database_userdata.sqlite:/app/database_userdata.sqlite
