apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: prakashh16/node-application-auth_service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "sqlite:///app/database_auth.sqlite"
          resources:  
            limits:
              cpu: "0.5"  
              memory: "512Mi"  
            requests:
              cpu: "0.1"  
              memory: "256Mi"  
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31001
  type: NodePort
